//
//  Strings.swift
//  PADI
//
//  Created by Thinh Mai on 12/26/19.
//  Copyright © 2019 PADI Worldwide Corp. All rights reserved.
//

import Foundation

enum Strings: String {
    case CommonCancel = "text_cancel"
    case CommonSearch = "search_hint"
    case CommonDelete = "confirm_delete"
    case CommonEmail = "hint_email_login_fragment"
    case CommonOK = "text_ok"
    case CommonOops = "text_oops"
    case CommonSkip = "text_skip"
    case CommonNext = "btn_next"
    case CommonDone = "text_done"
    case CommonEdit = "text_edit"
    case CommonProChek = "title_fragment_tool_procheck"
    case CommonInstructor = "instructor_detail_ecard_fragment"
    case CommonHandSignals = "title_fragment_tool_handsignal"
    case CommonSignIn = "signin_text"

    case UserDoesNotExist = "error_message_email_not_found"
    
    case LoginPasswordTextFieldPlaceHolder = "hint_pass_login_fragment"
    case LoginForgotPasswordText = "forgot_pass_login_fragment"
    case LoginLetGetBackInText = "content_title_login_fragment"
    case LoginInvalidEmailText = "Enter a valid email address."
    case LoginInvalidPasswordText = "Password must be at least 6 character."
    case LoginCanNotBeEmptyText = "Can not be empty."
    case LoginAlreadyHaveAnAccountTitle = "content_check_ready_account_text"
    case LoginErrorInvalidUserNamePasswordTitle = "incorrect_user_pass_login_fragment"

    case OnboardingWelcomeToPADIAppTitle = "onboarding_title[0]"
    case OnboardingWelcomeToPADIAppSubTitle = "onboarding_message[0]"
    case OnboardingAccesseCardsTitle = "onboarding_title[1]"
    case OnboardingAccesseCardsSubTitle = "onboarding_message[1]"
    case OnboardingHandSignalsTitle = "onboarding_title[3]"
    case OnboardingHandSignalsSubTitle = "onboarding_message[3]"

    
    case EcardDetailQualificationTitle = "dive_shop_qualification_text"
    case EcardDetailDiveShopTitle = "dive_shop_ecard_fragment"
    case EcardDetailInstructorNameTitle = "name_ecard_fragment"
    case EcardDetailPADINoInstructorTitle = "padi_no_ecard_fragment"
    case EcardDetailStudentDetailTitle = "student_detail_ecard_fragment"
    case EcardDetailDownloadEcardText = "text_download_ecard"
    case EcardDetailDiveShopAddressTitle = "address_ecard_fragment"
    case EcardDetailDiveShopPhoneTilte = "phone_ecard_fragment"
    case EcardDetailDiveShopWebsiteTitle = "website_ecard_fragment"
    case EcardDetailDiveShopAddressOpenMapText = "open_in_map_ecard_fragment"
    case EcardDetailStudentCellBirthDateTitle = "birthday_ecard_fragment"
    case EcardDetailStudentCellCertDateTitle = "cert_date_ecard_fragment"
    
    case EcardListeCardsTitle = "title_nav_ecard"
    case EcardListLoginRequireCreateAnAccountTitle = "sign_up_button"
    case EcardListSegmentViewAllTitle = "tab_view_all"
    case EcardListSegmentDownloadedTitle = "tab_downloaded"
    case EcardListDownloadedeCardsTitle = "Downloaded eCards"
    case EcardListLearnMoreTitle = "text_learn_more"
    case EcardListSelectAllTitle = "text_select_all"
    case EcardListeCardsSupportTitle = "eCards Support"
    case EcardListPromptDeleteYourDownloadedeCardMessage = "text_delete_ecard"
    case EcardListNoecardsYouHaveNoeCardsTitle = "no_ecards_title"
    case EcardListNoecardsYouHaveNoeCardsSubTitle = "message_ecard_empty"
    case EcardListNoecardsPurchaseeCardsTitle = "text_purchase_ecard"
    case EcardListNoecardseCardFAQTitle = "text_ecard_fqa"
    case EcardListNoDownloadedeCardsMessage = "no_item_title"
    case EcardListBottomViewSelectedTitle = "text_ecard_delete"
    
    case ToolsTitle = "title_nav_tools"
    case ToolsLogbookTitle = "title_fragment_tool_logbook"
    case ToolsLogbookDescText = "content_fragment_tool_logbook"
    case ToolsKnotsTitle = "title_fragment_tool_knots"
    case ToolsKnotsDescText = "content_fragment_tool_knots"
    case ToolsProCheckDescText = "content_fragment_tool_procheck"
    case ToolsHandSignalsDescText = "content_fragment_tool_handsignal"
    case ToolsChecklistsTitle = "title_fragment_tool_checklist"
    case ToolsChecklistsDescText = "content_fragment_tool_checklist"
    case ToolsChecklistsDiveDayTitle = "dive_day"
    case ToolsChecklistsDiveVacationTitle = "dive_vacation"
    case ToolsChecklistsSaveADayTitle = "dive_save_a_dive_kit"
    case ToolsChecklistsFirstAidTitle = "dive_first_aid_kit"
    case ToolsCheckListResetTitle = "toolbar_reset"
    
    case ProChekMemberNumberTitle = "prochek_member"
    case ProChekSubmitButtonTitle = "submit_button"
    case ProChekLearnMoreText = "learmore_prochek_title"

    case ProChekResultCredentialAuthorizedTechTitle = "author_to_teach_title"
    case ProChekResultCredentialRenewedTitle = "renew_year_title"
    case ProChekResultCredentialRenewedYearText = "renew_years_title"
    case ProChekResultPadiNoText = "procheck_ins_padino_title"
    case ProChekResultPadiRatingTitle = "padi_rating_title"
    case ProChekResultNotFoundText = "prochek_result_not_found_text"
    case ProChekResultSearchingText = "text_searching"
    
    case ProChekAboutTitle = "learn_ab_toolbar"
    case ProChekAboutDefinationText = "learn1_title"
    case ProChekAboutInstructorText = "learn3_title"
    case ProChekAboutDefDivemasterText = "learn4_title"
    case ProChekAboutNoteText = "learn5_title"
    case ProChekAboutPadiMemberText = "learn6_title"
    
    case MoreTitle = "title_nav_more"
    case MoreSignOutTitle = "sign_out_content_more"
    case MoreSignOutConfirmationMessageTitle = "account_sign_out_confirmation_text"
    case MoreAccountTitle = "account_content_more"
    case MoreAccountDetailsTitle = "account_detail_title"
    case MoreEditAccountDetailsTitle = "edit_account_detail_title"
    case MoreNotificationsTitle = "notification_content_more"
    case MoreSettingsTitle = "setting_content_more"
    case MoreSettingsLanguageTitle = "setting_language"
    case MoreSettingsUnitsTitle = "setting_unit_appbar"
    case MoreSettingsMetricTitle = "metric_setting"
    case MoreSettingsImperialTitle = "imperial_setting"
    case MoreSettingsBARTitle = "bar_unit"
    case MoreSettingsPSITitle = "psi_unit"
    case MoreSettingsMeasurementUnitsTitle = "measure_unit"
    case MoreSettingsDisplayInFeetTitle = "content_measure_unit"
    case MoreSettingsPressureUnitsTitle = "pressuare_unit"
    case MoreSettingsDisplayInMetresTitle = "content_measure_unit_in_metter"
    case MoreAboutTitle = "about_content_more"
    case MoreAboutPADIAppTitle = "padi_app_title"
    case MoreAboutVersionTitle = "padi_app_version_title"
    case MoreAboutLegalTitle = "padi_app_legal_title"
    case MoreAboutTermsOfServiceTitle = "padi_app_term_title"
    case MoreAboutPrivacy = "padi_app_privacy_title"
    case MoreAboutCopyRight = "padi_app_about_copyright_title"
    case MoreGeneralTitle = "general_title_more"
    case MoreSupportTitle = "support_title_more"
    case MoreHelpAndSupportTitle = "help_support_content_more"
    case MoreFeedbackTitle = "feedback_content_more"
    
    case LogoutStateInfoText = "Sign in or sign up for an account to begin logging dives."
    case LogoutStateSignUpTitle = "content_signup_button"
    case LogoutStateeCardInfoTitle = "ecard_content_unauthentication"
    case LogoutStateDiveChecklistsInfoTitle = "checklists_content_unauthentication"
    case LogoutStateAccountInfoTitle = "Sign in or sign up for an account to update your account information."
    
    case RatingAreYouEnjoyingPADITitle = "Are you enjoying PADI?"
    case RatingYesTitle = "Yes"
    case RatingNoTitle = "No"
    case RatingSubmitFeedbackToPadiTitle = "Would you like to submit feedback to PADI?"
    case RatingMaybeLaterTitle = "Maybe Later"
    
    case OfflineMessageText = "offline_mode_first_launching_error_text"
    case OfflineCannotReachText = "offline_mode_can_not_reach_text"
    case OfflineTitleText = "offline_mode_you_are_offline"
    case OfflineDescText = "offline_mode_desc_text"
    case ErrorText = "offline_mode_error"
    case DismissText = "offline_mode_dismiss"
    case UnknowErrorMsg = "Unknown error occurred. Please try again later!"

    case LogbookTrainingDiveTitle = "Training Dive"
    case LogbookHowToLogHeaderTitle = "How to log a Training Dive"
    case LogbookHowToLogHeaderDesc = "Complete all fields in the log entry, then submit it to your instructor for verification."
    case LogbookHowToVerificationTitle = "How Verification works"
    case LogbookHowToVerificationDesc = "After submitting a training dive, you will see one of the following status':"
    case LogbookVerificationStatusPendingTitle = "Pending"
    case LogbookVerificationStatusPendingDesc = "Received by your instructor and is pending verification."
    case LogbookVerificationStatusVerifiedTitle = "Verified"
    case LogbookVerificationStatusVerifiedDesc = "Your logged dive has been reviewed and verified by your instructor."
    case LogbookVerificationStatusResubmitTitle = "Resubmit"
    case LogbookVerificationStatusResubmitDesc = "Your instructor has requested edits to be made before verifying the dive."
    case LogbookNoItemsLoggedTitle = "You haven't logged any dives yet!"
    case LogbookNoItemsLoggedSubtitle = "Your dives will start to appear as you log them."
    case LogbookNoItemsButtonTitle = "Log a dive"
    
    case LogTypeTitle = "Dive Type"
    case LogTypeTrainingTitle = "Training"
    case LogTypeRecreationalTitle = "Recreational"
    
    func localize() -> String {
        return self.rawValue.localized
    }
}
